SELECT NAME, AREA FROM CONTINENT;

SELECT NAME, AREA, DEPTH FROM LAKE WHERE NAME = 'Lake Malawi';

SELECT NAME, AREA, DEPTH FROM LAKE ORDER BY DEPTH DESC;

SELECT NAME, AREA, DEPTH FROM LAKE WHERE DEPTH IS NOT NULL
ORDER BY DEPTH DESC;

SELECT NAME, ECONOMY.AGRICULTURE FROM COUNTRY INNER JOIN ECONOMY ON COUNTRY.CODE = ECONOMY.COUNTRY
WHERE ECONOMY.AGRICULTURE >= 50;

SELECT NAME FROM RIVER WHERE LENGTH = (SELECT MAX(LENGTH) FROM RIVER);